---
title: "Introduction to DiallelAnalysisR"
author: "Muhammad Yaseen^1^, and Kent M. Eskridge^2^"
date: "`r Sys.Date()`"
geometry: margin=3cm
output:
  pdf_document:
    dev: cairo_pdf
    fig_caption: no
    number_sections: no
    toc: no
  html_document:
    number_sections: yes
    toc: yes
documentclass: article
header-includes:
- \usepackage{fancyhdr}
- \usepackage{wrapfig}
- \usepackage{float}
- \pagestyle{fancy}
- \fancyfoot[C]{\thepage}
- \usepackage{hyperref}
- \hypersetup{colorlinks=true}
- \hypersetup{linktoc=all}
- \hypersetup{linkcolor=blue}
- \usepackage{pdflscape}
- \usepackage{booktabs}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \renewcommand\thesection{\arabic{section}}
link-citations: yes
csl: frontiers.csl
resource_files:
- vignettes/rbase.png
- vignettes/rstudio.png
- vignettes/rstudio panes.png
bibliography: Bibliography.bib
vignette: |
  %\VignetteIndexEntry{IntroDiallelAnalysisR}
  %\usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown_notangle}
---

```{r, echo=FALSE}
out_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")

r = getOption("repos")
r["CRAN"] = "https://cran.rstudio.com/"
#r["CRAN"] = "https://cloud.r-project.org/"
#r["CRAN"] = "https://ftp.iitm.ac.in/cran/"
options(repos = r)
```

```{r, results='asis', echo=FALSE}
switch(out_type,
    html = {cat("<p>1. Department of Mathematics and Statistics, University of Agriculture Faisalabad, Pakistan.</p>

<p>2.Department of Statistics, University of Nebraska Lincoln, NE, USA.</p>")},
    latex = cat("\\begin{center}
1. Department of Mathematics and Statistics, University of Agriculture Faisalabad, Pakistan.
2. Department of Statistics, University of Nebraska Lincoln, NE, USA

\\end{center}" )
)
```

\begin{center}
\vspace{6pt}
\hrule
\end{center}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "",
                      fig.cap = "")
```

\tableofcontents


# 1 Overview
This is a test

#  Session Info

```{r}
sessionInfo()
```

# References
